[pytest]
DJANGO_SETTINGS_MODULE = product.settings
python_files = tests.py *_test.py tests_*.py
testpaths = .
# Отключаем создание тестовой базы данных, если она уже существует
addopts = --reuse-db

# Отключаем автоматическое создание миграций
django_find_migrations = False