# Generated by Django 5.1.5 on 2025-02-02 12:05

import django.db.models.deletion
import goods.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_categories_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(
                max_length=150, unique=True, verbose_name='Наименование категории'
            ),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slag',
            field=models.SlugField(
                blank=True, max_length=200, null=True, unique=True, verbose_name='URL'
            ),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=150,
                        unique=True,
                        verbose_name='Наименование продукты',
                    ),
                ),
                (
                    'slag',
                    models.SlugField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name='URL',
                    ),
                ),
                (
                    'description',
                    models.TextField(blank=True, null=True, verbose_name='Отзыв'),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to='goods_images',
                        verbose_name='Изображение',
                    ),
                ),
                (
                    'price',
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=7, verbose_name='Цена'
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        default=goods.models.get_default_category_id,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to='goods.categories',
                        verbose_name='Категория',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'product',
            },
        ),
    ]
