# Generated by Django 5.1.5 on 2025-02-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_categories_options_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='slag',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='slag',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(
                max_length=150, unique=True, verbose_name='Наименование продукта'
            ),
        ),
    ]
