# Generated by Django 5.1.5 on 2025-02-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_rename_slag_categories_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name='Цена'
            ),
        ),
    ]
