# Generated by Django 5.1.5 on 2025-02-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена'
            ),
        ),
    ]
