# Generated by Django 5.1.5 on 2025-02-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_alter_products_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={
                'ordering': ('price',),
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.IntegerField(
                choices=[
                    (1, '1'),
                    (2, '2'),
                    (3, '3'),
                    (4, '4'),
                    (5, '5'),
                    (6, '6'),
                    (7, '7'),
                    (8, '8'),
                    (9, '9'),
                    (10, '10'),
                ],
                default=1,
                verbose_name='Рейтинг',
            ),
        ),
    ]
