# Generated by Django 5.1.5 on 2025-03-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_alter_products_options_products_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10, verbose_name='Цена'),
        ),
    ]
